In [ ]:
## Step 1: Import Required Libraries

In this section, we import all libraries needed for:
- Data handling
- Visualization
- Machine learning
- Evaluation

In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

Matplotlib is building the font cache; this may take a moment.

#Load Dataset

In [2]:
# Load dataset
df = pd.read_csv("diabetes.csv")

# Display first rows
df.head()

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0

In [3]:
# Dataset shape
print("Shape:", df.shape)

# Column info
df.info()

# Check missing values
df.isnull().sum()

Shape: (15000, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PatientID               15000 non-null  int64
 1   Pregnancies             15000 non-null  int64
 2   PlasmaGlucose           15000 non-null  int64
 3   DiastolicBloodPressure  15000 non-null  int64
 4   TricepsThickness        15000 non-null  int64
 5   SerumInsulin            15000 non-null  int64
 6   BMI                     15000 non-null  float64
 7   DiabetesPedigree        15000 non-null  float64
 8   Age                     15000 non-null  int64
 9   Diabetic                15000 non-null  int64
dtypes: float64(2), int64(8)
memory usage: 1.1 MB

PatientID                 0
Pregnancies               0
PlasmaGlucose             0
DiastolicBloodPressure    0
TricepsThickness          0
SerumInsulin              0
BMI                       0
DiabetesPedigree          0
Age                       0
Diabetic                  0
dtype: int64

In [4]:
# Fill missing numerical values with mean
df.fillna(df.mean(numeric_only=True), inplace=True)

# Fill missing categorical values with mode
for col in df.select_dtypes(include="object"):
    df[col].fillna(df[col].mode()[0], inplace=True)

print("Missing values handled!")

Missing values handled!

In [5]:
# Label Encoding for categorical columns
encoder = LabelEncoder()

for col in df.select_dtypes(include="object"):
    df[col] = encoder.fit_transform(df[col])

df.head()

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0

In [9]:
# Features and Target
X = df.drop("DiabetesPedigree", axis=1)
y = df["DiabetesPedigree"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (15000, 9)
y shape: (15000,)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data scaled!")

Data scaled!

In [12]:
log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_scaled, y_train)

print("Logistic Regression trained!")

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [13]:
# Predictions
y_pred_log = log_model.predict(X_test_scaled)

# Accuracy
log_accuracy = accuracy_score(y_test, y_pred_log)

print("Logistic Regression Accuracy:", log_accuracy)

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_log))

AttributeError: 'LogisticRegression' object has no attribute 'coef_'

In [ ]:
cm_log = confusion_matrix(y_test, y_pred_log)

disp = ConfusionMatrixDisplay(confusion_matrix=cm_log)
disp.plot()

plt.title("Logistic Regression Confusion Matrix")
plt.show()

In [ ]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

print("Random Forest trained!")

In [ ]:
y_pred_rf = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", rf_accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

In [ ]:
models = ["Logistic Regression", "Random Forest"]
accuracies = [log_accuracy, rf_accuracy]

plt.bar(models, accuracies)
plt.title("Model Comparison")
plt.ylabel("Accuracy")
plt.ylim(0,1)

plt.show()

In [ ]:
import joblib

joblib.dump(log_model, "logistic_model.pkl")
joblib.dump(rf_model, "random_forest_model.pkl")

print("Models saved!")